openapi: 3.0.0
info:
  title: Inventory
  version: 1.0.0
  contact:
    name: john
    url: 'https://www.github.com/johnfg2610/stockit'
    email: johnfg2610@gmail.com
  license:
    name: ISC
    url: 'https://github.com/johnfg2610/stockit/blob/master/LICENSE'
  description: Used to access inventory counts as well as brands and catalog items
servers:
  - url: 'http://localhost:3000'
paths:
  '/inventory/{catalogItemId}':
    parameters:
      - schema:
          type: string
        name: catalogItemId
        in: path
        required: true
        description: The catalog item to modify
    get:
      summary: Get the current amount of the item available
      tags:
        - inventory
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AmountAvailable'
              examples:
                example-1:
                  value:
                    amount: 32
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: ./Error.v1.yaml
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: ./Error.v1.yaml
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: ./Error.v1.yaml
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: ./Error.v1.yaml
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: ./Error.v1.yaml
      operationId: get-inventory-catalogItemId
      description: Gets the amount of items avalible in inventory of the requested catalogItem
    patch:
      summary: Update the amount of a item
      operationId: patch-inventory-catalogItemId
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AmountAvailable'
              examples: {}
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: ./Error.v1.yaml
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: ./Error.v1.yaml
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: ./Error.v1.yaml
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: ./Error.v1.yaml
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: ./Error.v1.yaml
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AmountChange'
            examples:
              example-1:
                value:
                  amountIncrease: 35
        description: ''
      description: Updates the amount of a item
      tags:
        - inventory
components:
  schemas:
    AmountAvailable:
      title: AmountAvailable
      type: object
      properties:
        amount:
          type: integer
    AmountChange:
      title: AmountChange
      type: object
      properties:
        amountChangeable:
          type: integer
  securitySchemes:
    jwt-auth:
      type: http
      scheme: bearer
      bearerFormat: JWT
security:
  - jwt-auth: []
tags:
  - name: brand
    description: Used to access or change brands
  - name: catalog
    description: Used to access or change catalog items
  - name: inventory
    description: Used to access or change inventory
