openapi: 3.0.0
info:
  title: Inventory
  version: '1.0'
  contact:
    name: john
    url: github.com/johnfg2610/stockit
    email: johnfg2610@gmail.com
  license:
    name: ISC
    url: 'https://github.com/johnfg2610/stockit/blob/master/LICENSE'
servers:
  - url: 'http://localhost:3000'
paths: {}
components:
  schemas: {}
  securitySchemes:
    JWT auth:
      type: http
      scheme: bearer
